---
title: "Human Research Ethics and The Belmont Report"
author: "Smelly Nematodes"
date: 2019-10-21
categories: ["Section 02", "Ethics Topic"]
tags: ["Section 02", "Human Subjects"]
thumbnailImage: https://unsplash.com/photos/dBI_My696Rk
thumbnailImagePosition: left
---

The National Research Act for the Protection of Human Subjects of Biomedical and Behavioral Research was signed into law in 1974, and without this act today, many more individuals may have passed away due to violation of basic human ethics in research experiments. The focus of this act revolved rules regarding human experiments, such as having respect for persons, beneficence, and justice Research experiments have previously targeted powerless individuals, so this act marked huge progress in scientific research.


(https://www.hhs.gov/ohrp/regulations-and-policy/belmont-report/read-the-belmont-report/index.html)
(https://research.calpoly.edu/HS-guidelines)

<!--more-->

When it comes to performing experiments on humans to collect valuable research data, the issue of ethics becomes present. There was no former outline of ethical guidelines for human experiments until 1974, when the National Research Act for the Protection of Human Subjects of Biomedical and Behavioral Research was signed into law (The Belmont Report). This Act was signed a year after the Tuskegee syphilis study was shut down due to public outrage. In this experiment, researchers refusing to treat black subjects with syphilis who were going blind, insane, or experiencing other major health complications (read more: https://www.stat150.blog/2019/10/data-ethics-and-the-tuskegee-syphilis-study/). However, human subjects facing a lack of ethical principles have been seen long before this particular experiment. In WWII, unwilling prisoners were exploited in Nazi concentration camps for research. Similarly, in the 19th and 20th centuries, poor ward patients were frequently seen as research subjects, whereas private patients received improved medical care. Research experiments throughout history targeted individuals who did not have the power to speak for themselves in a completely unethical way, so the creation of this act marked huge progress in the scientific field.

The basic ethical principles outlined has three main focus points: respect for persons, beneficence, and justice. When it comes to the first focus point - respect for persons - individuals should be able to have a voice in the research and have full knowledge of what they are participating in. This also means that persons with diminished autonomy, such as children or disabled subjects, are entitled to protection. The second main principle is beneficence, meaning that researchers have an obligation to secure the well-being of research subjects. This includes not harming the subjects in any way, regardless of the benefits that may come for others (such as those outside the experiment with a condition being studied). Further, researchers must be able to maximize potential benefits for research subjects while minimizing harm to the best of their ability. Lastly, research experiments must be just. This means subjects cannot be denied of beneficial treatment without a good reason (and project-interruption is not a good reason, as seen in the Tuskegee Syphilis study). 

A way researchers have gone about following these guidelines is the inclusion of applications and waivers for research participation. First, researchers must provide all information possible, including the weight of all risks and benefits that may be involved. Participation must also be voluntary - the only form of valid consent.

While there are many more principles outlined in the article, past violation of respect for individuals, beneficence, and justice are the main reasons behind the need to create protection for human subjects, which due to the incorporation of The National Research Act for the Protection of Human Subjects of Biomedical and Behavioral Research, potentially saved many lives.

Consistent with the Belmont Report, Cal Poly SLO has its own research criteria to evaluate research proposals. These criteria include (1) risks to subjects are minimized. Even though some matter of risk is inevitable, (2) these risks must be reasonable in relation to anticipated research benefits. (3) Selection of subjects must be equitable. When selecting a population, the “voluntariness” may be diminished when performing research on children, prisoners, persons with a disability, or economically disadvantaged people, to name a few. Other criteria include (4) informed consent for participants, (5) ensuring the safety of participants through monitoring research data to ensure the safety of the subjects, and (6) making sure the confidentiality of subjects and data are protected. It is also important that (7) vulnerable populations are protected by rights and welfare, as well as in regards to all subjects, (8) participants must have adequate knowledge on the study with any deception involved in the procedures included. It is vital for Cal Poly to outline these research criteria and to make sure all project proposals follow these criteria before the research is approved to ensure that the rights, privacy, and respect of individuals who are participating in the research are not violated.


