---
title: "Medical Fraud"
author: "Beamy Rhino"
date: 2019-10-21
categories: ["Section 01", "News"]
tags: ["Section 01", "Stats in the News", "Medical Research"]
---


Have you ever read something that suspiciously links a certain medicine or food or something random to a serious medical condition? As patients, we're taught that people in the medical field are trustworthy; however, some release very suspicious and questionable research conclusions that are complete frauds. John Carlisle is a statistical researcher and consultant anaesthetist working to help find and debunk fraud in medical research. In the following article, there is a  conversation about major incidents of research frauds and how researchers like Carlisle are using statistics to seek out the red flags of sketchy research practices. http://theconversation.com/how-one-nhs-anaesthetist-is-fighting-international-medical-research-fraud-124244


A recent article published by news website "The Conversation" describes how John Carlisle, an English anesthetist, is using statistics and data collecting methods to combat fraud in the medical research community. One of the most famous cases of medical fraud is the report published in 1998 linking the MMR vaccine to autism, which was found to be falsified. Carlisle's desire to fight medical fraud was kickstarted when Yoshitaka Fujii, a Japanese researcher, published some suspiciously-tidy data about medicines that combat nausea. Carlisle and his team investigated the data and found it to be false. Fujii was eventually fired and his published work was retracted.
 
Carlisle has since developed great statistical skills that enable him to discover medical fraud. His method includes investigating how RCTs (randomized, controlled clinical trials) are conducted and if there are any outside factors influencing data. For example, the method investigates how groups of people in an experiment are separated. Groups within an experiment, according to Carlisle, should be similar on average in all respects. An experiment with groups that are too similar or too different indicates fraud. P-values and standard deviations are used to discover differences.
 
The statistics given in this article greatly enhances the argument it makes, which is that medical fraud does exist, but is being uncovered. The article states that, in 2017, Carlisle analyzed over 5,000 RCTs. This helps us believe in what the article is saying; Carlisle is not a small, one-man operation, but has resources enough to examine thousands of trials. In addition, the article states that a medical journal in England receives RCTs and examines them using Carlisle's method. Their results show that 1 in 40 trials they receive are fraudulent. However, the article is not perfect.  It could have been improved by elaborating more on Carlisle's method or giving more specific examples of medical fraud and how it was discovered using the method.