---
title: "The Stanford Prison Experiment: A Total Fraud?"
author: "Peewee Ocelot"
date: 2019-10-21
categories: ["Section 02", "Data Study"]
tags: ["Section 02", "Human Subjects"]
thumbnailImage: https://cdn.vox-cdn.com/thumbor/1TaXjIzt28oZuXNOYYSyEFTE3VQ=/0x0:3152x2385/920x613/filters:focal(1324x941:1828x1445):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/60051557/GettyImages_2020760.0.jpg
thumbnailImagePosition: left
---

Many of the most famous studies and experiments of the past years have lacked the ethics to provide real insight into the topics at hand

> "I can list so many more textbook psychology findings that have either not replicated, or are currently in the midst of a serious reevaluation."
> - Brian Resnick

https://www.vox.com/2018/6/13/17449118/stanford-prison-experiment-fraud-psychology-replication

  Of the numerous studies conducted over the past few decades, the Stanford Prison Experiment has to be one of the most famous. Everything it revealed about human nature and the effects power can have on people has played a pretty quintessential role in the world today, going so far as to inspire similar studies, movies, and the turning point of some cases in a court room setting. As of recently however, it appears that this study, along with several other reputable ones, have lacked a certain level of ethics that would otherwise make it a legitimate experiment and now the public needs to be made aware that not all of the information conveyed by these experiments is entirely accurate. In Brian Resnick's article, "The Stanford Prison Experiment was Massively Influential. We Just Learned it was a Fraud" published on June 13th of 2018, the details initially left out in these studies to create a greater sense of a definitive outcome have finally been revealed
  In the Stanford Prison Experiment specifically, the conductors of the study were clearly trying to prove that unchecked power creates an abuse of power in any situation regardless of who's involved. In the attempt to prove this cause and effect relationship, the scientific minds behind the study were apparently willing to abandon some of the morals attached to delivering any sort of information to the public when they manipulated certain aspects of the experiment. For example, the students who were assigned to act as guards were taught to be brutal as opposed to just being placed in a position of superiority. This aspect of the experiment completely changes one's interpretation of the data as it becomes clear that there was no natural materialization of an abuse of power but rather a forced outcome. Furthermore, one of the most famous instances to take place in the experiment, the moment when one inmate goes into a screaming fit, was later reported to be an act of improvisation as the student claimed he was just doing what the researches wanted him to do. With the revelation of these details, it becomes more and more apparent that the Stanford Prison Experiment was not as ground breaking as society once believed it to be.
  It's incredibly important for the organizers of these experiments to relay information responsibly and conduct their studies legitimately. Misinformation can be detrimental to a society, especially when some of the findings from experiments like this have been used to influence the course of events as important as court cases. As the general public, it's also important to remember to take everything with a grain of salt and be sure to do as much research as possible before accepting someone else's conclusions on something.

![]https://cdn.vox-cdn.com/thumbor/1TaXjIzt28oZuXNOYYSyEFTE3VQ=/0x0:3152x2385/920x613/filters:focal(1324x941:1828x1445):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/60051557/GettyImages_2020760.0.jpg
